services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Torq\PimcoreExpressionTesterBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']

    Torq\PimcoreExpressionTesterBundle\Service\:
        resource: '../src/Service'
        public: true

    Torq\PimcoreExpressionTesterBundle\Service\ExpressionTesterService:
        arguments:
            $expressionLanguage: '@pimcore.calculated_value.expression_language'

    Torq\PimcoreExpressionTesterBundle\Webpack\WebpackEntryPointProvider:
        tags:
            - { name: pimcore_studio_ui.webpack_entry_point_provider }
